all:
	gcc -Wall -Werror -lm minls.c -o minls
	gcc -Wall -Werror -lm minget.c -o minget

minls:
	gcc -Wall -Werror -lm minls.c -o minls

minget:
	gcc -Wall -Werror -lm minget.c -o minget

clean:
	rm minls
	rm minget